import javax.swing.*;
import javax.swing.event.*;
import javax.swing.text.*;
import javax.swing.colorchooser.*;
import javax.swing.filechooser.*;
import javax.accessibility.*;
import java.awt.*;
import java.awt.event.*;
import java.beans.*;
import java.util.*;
import java.io.*;
import java.text.*;
import java.net.*;

/**
 *
 * @author  MBartels
 *
 * displays status messages
 */
public class JFrameStatusMsg extends javax.swing.JFrame {

    // Variables declaration - do not modify
    private javax.swing.JPanel jPanelStatusMsg;
    private javax.swing.JTextField jTexFieldStatusMsg;
    // End of variables declaration

    /** Creates new form JFrame */
    public JFrameStatusMsg() {
        super("SiTech firmware upload status");
        initComponents();
        screenPlacement.getInstance().center(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {
        jPanelStatusMsg = new javax.swing.JPanel();
        jTexFieldStatusMsg = new javax.swing.JTextField();

        getContentPane().setLayout(new AbsoluteLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanelStatusMsg.setLayout(new AbsoluteLayout());

        jTexFieldStatusMsg.setEditable(false);
        jPanelStatusMsg.add(jTexFieldStatusMsg, new AbsoluteConstraints(10, 10, 480, -1));

        getContentPane().add(jPanelStatusMsg, new AbsoluteConstraints(0, 0, 500, 40));

        pack();
    }

    private void exitForm(java.awt.event.WindowEvent evt) {
        setVisible(false);
    }

    public void updateMsg(String msg) {
        jTexFieldStatusMsg.setText(msg);
    }
}

